package:
  name: jutlautil
  version: "0.0.5"

source:
  url: https://files.pythonhosted.org/packages/82/3f/459c26adfc3a4b9503a147f883f256ae7eb40f61099929ca4e7a21318a0d/jutlautil-0.0.5.tar.gz

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7

about:
  home: https://github.com/amandeepjutla/jutlautil
  license: MIT
  summary: "Package for simple utilities that I find myself using in multiple projects."
